# Generated by Django 5.2.8 on 2025-12-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dermcase',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
