# Generated by Django 5.2.8 on 2025-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Аллергии'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chronic',
            field=models.TextField(blank=True, help_text='Хронические заболевания'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meds',
            field=models.TextField(blank=True, help_text='Постоянные препараты'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Муж'), ('female', 'Жен')], default='male', max_length=10),
            preserve_default=False,
        ),
    ]
