# Generated by Django 5.2.8 on 2025-11-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_allergies_userprofile_chronic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contraindications',
            field=models.TextField(blank=True, help_text='Например: нельзя НПВС, аллергия на пенициллин и т.д.', verbose_name='Противопоказания к лекарствам'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chronic',
            field=models.TextField(blank=True, verbose_name='Хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='meds',
            field=models.TextField(blank=True, verbose_name='Постоянные препараты'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pregnant',
            field=models.BooleanField(default=False, verbose_name='Беременность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('мужской', 'Мужской'), ('женский', 'Женский'), ('не указан', 'Предпочитаю не указывать')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoker',
            field=models.BooleanField(default=False, verbose_name='Курение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
    ]
