# Generated by Django 5.2.8 on 2025-11-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_contraindications_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contraindications',
            field=models.TextField(blank=True, help_text='Например: НПВС противопоказаны, аллергия на пенициллин и т.д.', verbose_name='Противопоказания к лекарствам'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя / как к вам обращаться'),
        ),
    ]
